// https://yarduon.com
export default {
  es: [
    "Opciones",
    "1er temporizador",
    "Minutos",
    "Segundos",
    "2ndo temporizador",
    "Minutos",
    "Segundos",
    "Modo ganador",
    "Puntos",
    "Modo total",
    "Puntos",
    "Texto personalizado",
    "Mostrar nombres",
    "Descargar resultados",
    "Guardar",
    "Reiniciar",
    "Versión 1.6",
    "29/09/2024",
  ],
  fr: [
    "Options",
    "1ème minuterie",
    "Minutes",
    "Secondes",
    "2ème minuterie",
    "Minutes",
    "Secondes",
    "Mode gagnant",
    "Points",
    "Mode total",
    "Points",
    "Texte personnalisé",
    "Afficher les noms",
    "Téléchargez les résultats",
    "Sauvegarder",
    "Redémarrer",
    "Version 1.6",
    "29/09/2024",
  ],
  de: [
    "Optionen",
    "Erster Timer",
    "Minuten",
    "Sekunden",
    "Zweiter Timer",
    "Minuten",
    "Sekunden",
    "Gewinnmodus",
    "Punkte",
    "Vollmodus",
    "Punkte",
    "Benutzerdefinierter Text",
    "Namen zeigen",
    "Ergebnisse herunterladen",
    "Speichern",
    "Neu starten",
    "Version 1.6",
    "2024/09/29",
  ],
};
